### ISSUE TITLE
highlight broken when using a baseurl

### ISSUE THREAD

**Issue by lzubiaur** [octopress/solarized#3]
Hi, I'm an octopress noob so I apologies if I'm missing something but I'm trying to get the solarized highlight working with a baseurl without success. The demo works fine but once I try to set a baseurl the highlight doesn't work anymore because of the broken css url.

Although I defined a baseurl the css is still included without that base url.
```
<link href='/stylesheets/all-7c164891a277a5dda97ada0a56742417.css' media='all' rel='stylesheet' type='text/css'>
```

My steps:
1. Clone the solarized repo
```
# git clone https://github.com/octopress/solarized.git
```
2. Go to the demo folder and edit _config.yml to add a baseurl 
```
baseurl: '/test'
```
3. Start jekyll (jekyll serve) and open http://localhost:4000/test/

**Comment by imathis** [comment]
Good catch! Thanks I'll look into it.

**Comment by imathis** [comment]
You should be able to `bundle update` and your urls will be expanded with the baseurl. Let me know if there's any trouble.

**Comment by lzubiaur** [comment]
It's fixed. Thanks you for your quick response!

**Comment by imathis** [comment]
Woo hoo! Thanks for helping me find the bug!
