### ISSUE TITLE
How can I enable solarized light theme?

### ISSUE THREAD

**Issue by e9t** [octopress/solarized#4]
I've enabled solarized, but it's default seems to be dark.
I see that the light styles are included within the source code, but not sure how to enable it.
How do I change it to light?

btw. Thanks for Octopress 3. It's way cleaner and easier than 2.

**Comment by jdnavarro** [comment]
I had the same question but found out that with `octopress ink` you can do this:

```
$ octopress ink copy solarized --config
```

Then edit `_plugins/solarized/config.yml` and change the style from `dark` to `light`.

**Comment by e9t** [comment]
Thanks for the info! I'll try what you said as soon as I get my asset-pipeline problem fixed (https://github.com/octopress/asset-pipeline/issues/19).

**Comment by e9t** [comment]
Thanks @jdnavarro for the tip!
